export const customerData = [
  {
    id: "#4987",
    name: "Jordan Stevenson",
    email: "jordan@example.com",
    phone: "123-987654",
    company: "linkedin",
  },

  {
    id: "#4988",
    name: "Stephanie Burns",
    email: "brenda49@taylor.info",
    phone: "123-987654",
    company: "linkedin",
  },
  {
    id: "#4989",
    name: "Tony Herrera",
    email: "smithtiffany@powers.com",
    phone: "123-987654",
    company: "oxcytech",
  },
  {
    id: "#4990",
    name: "Kevin Patton",
    email: "mejiageorge@lee-perez.com",
    phone: "123-987654",
    company: "oxcytech",
  },
  {
    id: "#4988",
    name: "Stephanie Burns",
    email: "brenda49@taylor.info",
    phone: "123-987654",
    company: "linkedin",
  },
  {
    id: "#4987",
    name: "Jordan Stevenson",
    email: "jordan@example.com",
    phone: "123-987654",
    company: "linkedin",
  },
  {
    id: "#4991",
    name: "Mrs. Julie Donovan MD",
    email: "brandon07@pierce.com",
    phone: "123-987654",
    company: "oxcytech",
  },
  {
    id: "#4992",
    name: "Amanda Phillips",
    email: "guerrerobrandy@beasley-harper.com",
    phone: "123-987654",
    company: "oxcytech",
  },
  {
    id: "#4993",
    name: "Christina Collier",
    email: "williamshenry@moon-smith.com",
    phone: "123-987654",
    company: "oxcytech",
  },
  {
    id: "#4994",
    name: "David Flores",
    email: "margaretharvey@russell-murray.com",
    phone: "123-987654",
    company: "oxcytech",
  },
  {
    id: "#4995",
    name: "Valerie Perez",
    email: "dianarodriguez@villegas.com",
    phone: "123-987654",
    company: "oxcytech",
  },
  {
    id: "#4996",
    name: "Susan Dickerson",
    email: "bwilson@norris-brock.com",
    phone: "123-987654",
    company: "oxcytech",
  },
];
