export const indianStates = [
  { label: "Andhra Pradesh" },
  { label: "Arunachal Pradesh" },
  { label: "Assam" },
  { label: "Bihar" },
  { label: "Chhattisgarh" },
  { label: "Goa" },
  { label: "Gujarat" },
  { label: "Haryana" },
  { label: "Himachal Pradesh" },
  { label: "Jharkhand" },
  { label: "Karnataka" },
  { label: "Kerala" },
  { label: "Madhya Pradesh" },
  { label: "Maharashtra" },
  { label: "Manipur" },
  { label: "Meghalaya" },
  { label: "Mizoram" },
  { label: "Nagaland" },
  { label: "Odisha" },
  { label: "Punjab" },
  { label: "Rajasthan" },
  { label: "Sikkim" },
  { label: "Tamil Nadu" },
  { label: "Telangana" },
  { label: "Tripura" },
  { label: "Uttar Pradesh" },
  { label: "Uttarakhand" },
  { label: "West Bengal" },
];
